/*
 * File: app/store/NavigatorStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Duyun.store.Navigator', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'Duyun.model.Navigator'
    ],
    
    model: 'Duyun.model.Navigator',
        
    proxy: {
        type: 'ajax',
        url: 'data/Navigator.json',
        reader: {
            type: 'json',
            root: 'children'
        }
    }
});