/*
 * File: app/view/PhoneNumberPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Duyun.view.PhoneNumberPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.phonenumber',

    draggable: true,
    frame: true,
    height: 220,
    width: 400,
    bodyPadding: '5,5,0',
    closable: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    height: 148,
                    padding: '5px',
                    defaultType: 'textfield',
                    defaults: {
                        anchor: '100%',
                        labelWidth: 75
                    },
                    title: 'Phone Number',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'home',
                            fieldLabel: 'Home'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'business',
                            fieldLabel: 'Business'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'mobile',
                            fieldLabel: 'Mobile'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'fax',
                            fieldLabel: 'Fax'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    defaults: 'minWidth: minButtonWidth',
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            id: 'btnSave',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            id: 'btnCancel',
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});