/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Duyun.controller.Main', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'navigator',
            selector: '#pnlNavigation',
            xtype: 'treepanel'
        },
        {
            ref: 'mainPanel',
            selector: '#pnlCenter',
            xtype: 'panel'
        }
    ],

    init: function(application) {
        this.control({
            'viewport > treepanel':{
                select: function(me, record, item, index, e){                  
                    if (!record.isLeaf()) {
                        return;
                    }

                    console.log(record.get('view'));
                    console.log(this.classNameFromRecord(record));
                    this.setActivePanel(this.classNameFromRecord(record), application);
                }
            }

        });

    },

    setActivePanel: function(className, application) {
//        var centerPanel = this.getMainPanel(), panel;    
//
//        panel = Ext.create(className);
//
//        centerPanel.removeAll();
//        centerPanel.add(panel);
    	var ctrlName = className.split('.').slice(2).join('.');
    	console.log(ctrlName);
    	Ext.require(className, function(){
            var controller = application.getController(ctrlName);
            controller.init(application);
        },self);
    },

    classNameFromRecord: function(record) {
        var path = this.filePathFromRecord(record);

//        path = 'Duyun.view.' + path.replace('/', '.');
        path = 'Duyun.controller.' + path.replace('/', '.');
        return path;
    },

    filePathFromRecord: function(record) {
        var parentNode = record.parentNode,
        path = record.get('view');

        while (parentNode && parentNode.get('text') != "Root") {
            path = parentNode.get('view') + '/' + Ext.String.capitalize(path);

            parentNode = parentNode.parentNode;
        }

        return path;
    }

});
